version: "3"
services:
  springboot:
    container_name: mallook-api
    image: duckbill413/mallook-docker-api:latest
    ports:
      - "127.0.0.1:8080:8080"
      - "8081:8081"
    environment:
      TZ: "Asia/Seoul"
    networks:
      - mallook_net
    volumes:
      - /home/ec2-user/logs:/logs

  mallook-batch:
    container_name: mallook-batch
    image: duckbill413/mallook-docker-batch:latest
    environment:
      TZ: Asia/Seoul
    networks:
      - mallook_net
    depends_on:
      - springboot

  redis:
    image: redis:alpine
    container_name: mallook-redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - mallook_net
    restart: always

  nginx:
    container_name: mallook-nginx
    image: duckbill413/mallook-nginx:latest
    build:
      context: ./back/mallook/nginx
      dockerfile: nginxDockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mallook_net
    depends_on:
      - springboot

  nextjs:
    container_name: mallook-nextjs
    image: duckbill413/mallook-nextjs:latest
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - mallook_net

networks:
  mallook_net:
    driver: bridge

